### ISSUE TITLE
consistent column names in sppEquivalencies_CA

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/pemisc#2]
with #1 

use consistent column names in `sppEquivalencies_CA`:

1. I'm OK with colnames being Snake_Case instead of camelCase;
2. do we need 'names' in the colname? why not simply use e.g., `LANDIS_test`?
3. `shortENGeneric` and `full.ENGeneric` should be consistent: e.g., `EN_generic_short`

I propose the following:

- `LANDIStest_names` ==> `LANDIS_test`
- `LANDIStraits_names` ==> `LANDIS_traits`
- `LandR_names` ==> `LandR`
- `KNN_names` ==> `kNN`
- `CASFRI_names` ==> `CASFRI`
- `fullLatin` ==> `Latin_full`
- `shortENGeneric` ==> `EN_Generic_short`
- `full.ENGeneric` ==> `EN_Generic_full`
- `leadingNames` ==> `Leading`
- `Notes` (as is)

**Comment by CeresBarros** [comment]
Done -> d43cf04

**Comment by achubaty** [comment]
documentation not yet updated.

(a reminder that you can tag the issue number in the commit to link it to here, _e.g._, `#2`)

**Comment by CeresBarros** [comment]
I _believe_ all is good now.

**Comment by achubaty** [comment]
docs done in 9fefc4e1953500075ae9dc26d5a8cdb73f8ca947
